## Fetching data from [Open-Meteo Historical Weather API ](https://open-meteo.com/en/docs/historical-weather-api).

In [2]:
import openmeteo_requests
import requests_cache
import pandas as pd
from retry_requests import retry
import fastparquet

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 45.7537,
	"longitude": 21.2257,
	"start_date": "2000-01-01",
	"end_date": "2024-10-23",
	"hourly": ["weather_code", "temperature_2m", "relative_humidity_2m", "precipitation", "wind_speed_10m", "wind_direction_10m", "wind_gusts_10m"],
	"daily": ["weather_code", "temperature_2m_max", "temperature_2m_min", "temperature_2m_mean", "precipitation_sum", "wind_speed_10m_max", "wind_gusts_10m_max", "wind_direction_10m_dominant"],
	"timezone": "auto"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print("Details about Timisoara weather (hourly and daily) between 2000-2024")
print(f"Coordinates {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
hourly_precipitation = hourly.Variables(2).ValuesAsNumpy()
hourly_weather_code = hourly.Variables(3).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(4).ValuesAsNumpy()
hourly_wind_direction_10m = hourly.Variables(5).ValuesAsNumpy()
hourly_wind_gusts_10m = hourly.Variables(6).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
	end = pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}
hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
hourly_data["precipitation"] = hourly_precipitation
hourly_data["weather_code"] = hourly_weather_code
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
hourly_data["wind_direction_10m"] = hourly_wind_direction_10m
hourly_data["wind_gusts_10m"] = hourly_wind_gusts_10m

hourly_dataframe = pd.DataFrame(data = hourly_data)

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_weather_code = daily.Variables(0).ValuesAsNumpy()
daily_temperature_2m_max = daily.Variables(1).ValuesAsNumpy()
daily_temperature_2m_min = daily.Variables(2).ValuesAsNumpy()
daily_temperature_2m_mean = daily.Variables(3).ValuesAsNumpy()
daily_precipitation_sum = daily.Variables(4).ValuesAsNumpy()
daily_wind_speed_10m_max = daily.Variables(5).ValuesAsNumpy()
daily_wind_gusts_10m_max = daily.Variables(6).ValuesAsNumpy()
daily_wind_direction_10m_dominant = daily.Variables(7).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
	end = pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}
daily_data["weather_code"] = daily_weather_code
daily_data["temperature_2m_max"] = daily_temperature_2m_max
daily_data["temperature_2m_min"] = daily_temperature_2m_min
daily_data["temperature_2m_mean"] = daily_temperature_2m_mean
daily_data["precipitation_sum"] = daily_precipitation_sum
daily_data["wind_speed_10m_max"] = daily_wind_speed_10m_max
daily_data["wind_gusts_10m_max"] = daily_wind_gusts_10m_max
daily_data["wind_direction_10m_dominant"] = daily_wind_direction_10m_dominant

daily_dataframe = pd.DataFrame(data = daily_data)
# print df shapes
print("""
      .
      .
      .
""")
print(f"Hourly dataframe shape: {hourly_dataframe.shape}. Null values: \n{hourly_dataframe.isna().sum()}\nDaily dataframe shape: {daily_dataframe.shape}. Null values: \n{daily_dataframe.isna().sum()}")
print("""
      .
      .
      .
""")
print("Cleaning dataframes...")
hourly_dataframe.dropna(inplace=True)
print("hourly_dataframe cleaned.")
print(f"Null values: {hourly_dataframe.isna().sum()}")

daily_dataframe.dropna(inplace=True)
print("daily_dataframe cleaned.")
print(f"Null values: {daily_dataframe.isna().sum()}")

Details about Timisoara weather (hourly and daily) between 2000-2024
Coordinates 45.729347229003906°N 21.29337501525879°E
Elevation 96.0 m asl
Timezone b'Europe/Bucharest' b'EEST'
Timezone difference to GMT+0 10800 s

      .
      .
      .

Hourly dataframe shape: (217512, 8). Null values:
date                     0
temperature_2m          44
relative_humidity_2m    44
precipitation           44
weather_code            44
wind_speed_10m          44
wind_direction_10m      44
wind_gusts_10m          44
dtype: int64
Daily dataframe shape: (9063, 9). Null values:
date                           0
weather_code                   1
temperature_2m_max             1
temperature_2m_min             1
temperature_2m_mean            2
precipitation_sum              2
wind_speed_10m_max             1
wind_gusts_10m_max             1
wind_direction_10m_dominant    2
dtype: int64

      .
      .
      .

Cleaning dataframes...
hourly_dataframe cleaned.
Null values: date                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
weather_code            0
wind_speed_10m          0
wind_direction_10m      0
wind_gusts_10m          0
dtype: int64
daily_dataframe cleaned.
Null values: date                           0
weather_code                   0
temperature_2m_max             0
temperature_2m_min             0
temperature_2m_mean            0
precipitation_sum              0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
dtype: int64

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

#### Data cleaning, exploratory data analysis for **Hourly dataframe**

In [35]:
hourly_dataframe.head()

,date,temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m
0,1999-12-31 21:00:00+00:00,3.0,-1.128,86.920624,0.0,13.722565,355.486084,25.199999
1,1999-12-31 22:00:00+00:00,3.0,-1.328,86.577271,0.0,12.287555,354.957642,25.559999
2,1999-12-31 23:00:00+00:00,3.0,-1.778,87.833557,0.0,12.496719,348.366394,24.480000
3,2000-01-01 00:00:00+00:00,3.0,-1.978,87.486717,0.0,12.849528,348.690094,23.400000
4,2000-01-01 01:00:00+00:00,3.0,-2.128,86.170082,0.0,12.758432,343.610382,24.840000

In [37]:
hourly_dataframe.dropna(inplace=True)
hourly_dataframe.isna().sum()

date                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
weather_code            0
wind_speed_10m          0
wind_direction_10m      0
wind_gusts_10m          0
dtype: int64

#### Data cleaning, exploratory data analysis for **Daily dataframe**

In [38]:
daily_dataframe.head()

,date,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,1999-12-31 21:00:00+00:00,3.0,1.022,-3.178,-1.711334,0.0,14.003029,29.519999,334.442993
1,2000-01-01 21:00:00+00:00,3.0,1.472,-3.528,-1.278000,0.0,9.007196,19.440001,15.975966
2,2000-01-02 21:00:00+00:00,3.0,-0.228,-4.928,-2.430083,0.0,7.091177,18.719999,244.041290
3,2000-01-03 21:00:00+00:00,3.0,1.922,-1.078,0.167833,0.0,5.860375,14.400000,173.779129
4,2000-01-04 21:00:00+00:00,3.0,1.872,-1.078,0.063667,0.0,7.704336,16.919998,243.012177

In [39]:
daily_dataframe.dropna(inplace=True)
print("Cleaned.")
daily_dataframe.isna().sum()

Cleaned.

date                           0
weather_code                   0
temperature_2m_max             0
temperature_2m_min             0
temperature_2m_mean            0
precipitation_sum              0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
dtype: int64

In [5]:
hourly_dataframe.to_parquet(r"/workspaces/weather-scraper-analyzer/data/hourly_dataframe.gzip", compression='gzip')
print("Saved hourly dataframe to data folder")
daily_dataframe.to_parquet(r"/workspaces/weather-scraper-analyzer/data/daily_dataframe.gzip", compression='gzip')
print("Saved hourly dataframe to data folder")

Saved hourly dataframe to data folder
Saved hourly dataframe to data folder

# <font color='red'>I WANT TO VERIFY WTF IS HAPPENING WITH THOSE HOURLY COLUMNS (seems they are like mixed up or smth) </font>
#### [Go to analyze_data_notebook.ipynb](/workspaces/weather-scraper-analyzer/notebooks/03-data_analysis/analyze_data_notebook.ipynb#section-header) ==> Here the columns are mixed up @ hourly_df.

### **I will fetch the data again!**

In [1]:
import openmeteo_requests

import requests_cache
import pandas as pd
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 45.7537,
	"longitude": 21.2257,
	"start_date": "2000-01-01",
	"end_date": "2024-10-23",
	"hourly": ["temperature_2m", "relative_humidity_2m", "precipitation", "weather_code", "wind_speed_10m", "wind_direction_10m", "wind_gusts_10m"],
	"daily": ["weather_code", "temperature_2m_max", "temperature_2m_min", "temperature_2m_mean", "precipitation_sum", "wind_speed_10m_max", "wind_gusts_10m_max", "wind_direction_10m_dominant"],
	"timezone": "auto"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
hourly_precipitation = hourly.Variables(2).ValuesAsNumpy()
hourly_weather_code = hourly.Variables(3).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(4).ValuesAsNumpy()
hourly_wind_direction_10m = hourly.Variables(5).ValuesAsNumpy()
hourly_wind_gusts_10m = hourly.Variables(6).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
	end = pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}
hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
hourly_data["precipitation"] = hourly_precipitation
hourly_data["weather_code"] = hourly_weather_code
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
hourly_data["wind_direction_10m"] = hourly_wind_direction_10m
hourly_data["wind_gusts_10m"] = hourly_wind_gusts_10m

hourly_dataframe = pd.DataFrame(data = hourly_data)

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_weather_code = daily.Variables(0).ValuesAsNumpy()
daily_temperature_2m_max = daily.Variables(1).ValuesAsNumpy()
daily_temperature_2m_min = daily.Variables(2).ValuesAsNumpy()
daily_temperature_2m_mean = daily.Variables(3).ValuesAsNumpy()
daily_precipitation_sum = daily.Variables(4).ValuesAsNumpy()
daily_wind_speed_10m_max = daily.Variables(5).ValuesAsNumpy()
daily_wind_gusts_10m_max = daily.Variables(6).ValuesAsNumpy()
daily_wind_direction_10m_dominant = daily.Variables(7).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s", utc = True),
	end = pd.to_datetime(daily.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}
daily_data["weather_code"] = daily_weather_code
daily_data["temperature_2m_max"] = daily_temperature_2m_max
daily_data["temperature_2m_min"] = daily_temperature_2m_min
daily_data["temperature_2m_mean"] = daily_temperature_2m_mean
daily_data["precipitation_sum"] = daily_precipitation_sum
daily_data["wind_speed_10m_max"] = daily_wind_speed_10m_max
daily_data["wind_gusts_10m_max"] = daily_wind_gusts_10m_max
daily_data["wind_direction_10m_dominant"] = daily_wind_direction_10m_dominant

daily_dataframe = pd.DataFrame(data = daily_data)

# print df shapes
print("""
      .
      .
      .
""")
print(f"Hourly dataframe shape: {hourly_dataframe.shape}. Null values: \n{hourly_dataframe.isna().sum()}\nDaily dataframe shape: {daily_dataframe.shape}. Null values: \n{daily_dataframe.isna().sum()}")
print("""
      .
      .
      .
""")
print("Cleaning dataframes...")
hourly_dataframe.dropna(inplace=True)
print("hourly_dataframe cleaned.")
print(f"Null values: {hourly_dataframe.isna().sum()}")

daily_dataframe.dropna(inplace=True)
print("daily_dataframe cleaned.")
print(f"Null values: {daily_dataframe.isna().sum()}")

Coordinates 45.729347229003906°N 21.29337501525879°E
Elevation 96.0 m asl
Timezone b'Europe/Bucharest' b'EEST'
Timezone difference to GMT+0 10800 s

      .
      .
      .

Hourly dataframe shape: (217512, 8). Null values:
date                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
weather_code            0
wind_speed_10m          0
wind_direction_10m      0
wind_gusts_10m          0
dtype: int64
Daily dataframe shape: (9063, 9). Null values:
date                           0
weather_code                   0
temperature_2m_max             0
temperature_2m_min             0
temperature_2m_mean            0
precipitation_sum              0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
dtype: int64

      .
      .
      .

Cleaning dataframes...
hourly_dataframe cleaned.
Null values: date                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
weather_code            0
wind_speed_10m          0
wind_direction_10m      0
wind_gusts_10m          0
dtype: int64
daily_dataframe cleaned.
Null values: date                           0
weather_code                   0
temperature_2m_max             0
temperature_2m_min             0
temperature_2m_mean            0
precipitation_sum              0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
dtype: int64

### NO NULL Values to clean in the first place, comparing to the first time I fetched the data... 
Maybe because before I hit run (the first time) i modified manually the order of the parameters in the pre-written code from the API

In [2]:
hourly_dataframe.describe()

,temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m
count,217512.000000,217512.000000,217512.000000,217512.000000,217512.000000,217512.000000,217512.000000
mean,12.539617,71.552376,0.077676,8.602716,8.883139,188.770493,18.762188
std,9.546809,18.169477,0.338858,19.002098,4.722311,105.352600,9.381058
min,-23.377998,14.915503,0.000000,0.000000,0.000000,0.658531,1.080000
25%,5.022000,58.301290,0.000000,0.000000,5.771239,105.945465,11.879999
50%,12.622000,74.064152,0.000000,1.000000,7.895416,178.727005,16.199999
75%,19.802500,87.160080,0.000000,3.000000,11.183201,288.138184,23.759998
max,39.872002,100.000000,13.300000,75.000000,39.831684,360.000000,91.439995

In [3]:
hourly_dataframe.head()

,date,temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m
0,1999-12-31 21:00:00+00:00,-1.128,86.920624,0.0,3.0,13.722565,355.486084,25.199999
1,1999-12-31 22:00:00+00:00,-1.328,86.577271,0.0,3.0,12.287555,354.957642,25.559999
2,1999-12-31 23:00:00+00:00,-1.778,87.833557,0.0,3.0,12.496719,348.366394,24.480000
3,2000-01-01 00:00:00+00:00,-1.978,87.486717,0.0,3.0,12.849528,348.690094,23.400000
4,2000-01-01 01:00:00+00:00,-2.128,86.170082,0.0,3.0,12.758432,343.610382,24.840000

In [4]:
daily_dataframe.describe()

,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
count,9063.000000,9063.000000,9063.000000,9063.000000,9063.000000,9063.000000,9063.000000,9063.000000
mean,28.810879,17.305174,7.994661,12.539617,1.864228,13.723712,28.689493,189.336319
std,28.189657,9.698961,8.094123,8.908824,4.131135,5.303952,10.436808,106.242851
min,0.000000,-11.378000,-23.377998,-16.900917,0.000000,3.600000,8.280000,0.000005
25%,2.000000,9.672000,1.572000,5.423042,0.000000,9.605998,20.519999,110.953640
50%,3.000000,17.872002,8.272000,12.938667,0.000000,12.682018,27.359999,178.174820
75%,53.000000,25.272001,14.872000,20.003917,1.700000,16.808570,35.279999,289.000931
max,75.000000,39.872002,26.902500,31.942085,42.300003,39.831684,91.439995,359.999969

In [5]:
daily_dataframe.head()

,date,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,1999-12-31 21:00:00+00:00,3.0,1.022,-3.178,-1.711334,0.0,14.003029,29.519999,334.442993
1,2000-01-01 21:00:00+00:00,3.0,1.472,-3.528,-1.278000,0.0,9.007196,19.440001,15.975966
2,2000-01-02 21:00:00+00:00,3.0,-0.228,-4.928,-2.430083,0.0,7.091177,18.719999,244.041290
3,2000-01-03 21:00:00+00:00,3.0,1.922,-1.078,0.167833,0.0,5.860375,14.400000,173.779129
4,2000-01-04 21:00:00+00:00,3.0,1.872,-1.078,0.063667,0.0,7.704336,16.919998,243.012177

### Now everything seems to be in correct order!
#### Next step, store the data in weather_data.db

In [8]:
import sqlite3

conn = sqlite3.connect("/workspaces/weather-scraper-analyzer/data/weather_data.db")

hourly_dataframe.to_sql("hourly_data", conn, if_exists='replace')
daily_dataframe.to_sql("daily_data", conn, if_exists='replace')
c = conn.cursor()
c.execute("DROP TABLE daily_dataframe;")
print("Done")

Done

In [14]:
c.execute("""
        SELECT COUNT(*) AS no_rows_hourly_data FROM hourly_data
        UNION ALL
        SELECT COUNT(*) AS no_rows_daily_data FROM daily_data;
          """)
print(c.fetchall())

print("No rows hourly dataframe ", hourly_dataframe.shape[0])
print("No rows daily dataframe ", daily_dataframe.shape[0])

conn.close()
print("Connection closed.")

[(217512,), (9063,)]
No rows hourly dataframe  217512
No rows daily dataframe  9063
Connection closed.

# <font color='green'> **ALL FUCKING GOOD LET'S GOOOOOOOOO** </font>

## Continuing work on [analyze_data_notebook.ipynb](/workspaces/weather-scraper-analyzer/notebooks/03-data_analysis/analyze_data_notebook.ipynb)